# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  #  adapter: redis
#  url: redis://localhost:6379/1
  url: ENV['REDISTOGO_URL']

development:
  #adapter: async
  url: redis://localhost:6379/2

test:
  #adapter: async
  url: redis://localhost:6379/3
