# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33303a7427fad32c8e03d35ba27be90075ce84559ce91dfb1b4780fa779e0684854cf7771ef0f756bb07f2fb171f0a3f3852f521de9f2e0efcabf6a84f65f270

test:
  secret_key_base: 353932c8813ff28632f541ec708000d25bbd2d261dbfe28bf36d100e192ba6f07b07b06630274041aa63f0f282bee31d501fc4c507bba2f4feedf648e9bea277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
